name: Aerospace Vertical CI

on:
  push:
    paths:
      - 'verticals/aerospace/**'
      - 'core/**'
      - 'operators/**'
  pull_request:
    paths:
      - 'verticals/aerospace/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy torch>=2.3 jax>=0.4.28 scipy>=1.11
    
    - name: Run aerospace tests
      run: |
        PYTHONPATH=. pytest verticals/aerospace/tests/ -v
    
    - name: Run CFD benchmarks
      run: |
        PYTHONPATH=. python verticals/aerospace/benchmarks/cfd_convergence_bench.py --quick

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Lint
      run: |
        pip install ruff mypy
        ruff check verticals/aerospace/
        mypy verticals/aerospace/ --ignore-missing-imports
