name: Finance Vertical CI

on:
  push:
    paths:
      - 'verticals/finance/**'
      - 'core/**'
      - 'quantum_bridge/**'
  pull_request:
    paths:
      - 'verticals/finance/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy torch>=2.3 jax>=0.4.28 pandas>=2.0
    
    - name: Run finance tests
      run: |
        PYTHONPATH=. pytest verticals/finance/tests/ -v
    
    - name: Run Monte Carlo benchmarks
      run: |
        PYTHONPATH=. python verticals/finance/benchmarks/options_pricing_bench.py --quick

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Lint
      run: |
        pip install ruff mypy
        ruff check verticals/finance/
        mypy verticals/finance/ --ignore-missing-imports
