name: Telecom Vertical CI

on:
  push:
    paths:
      - 'verticals/telecom/**'
      - 'core/**'
  pull_request:
    paths:
      - 'verticals/telecom/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy torch>=2.3 scipy>=1.11 networkx>=3.0
    
    - name: Run telecom tests
      run: |
        PYTHONPATH=. pytest verticals/telecom/tests/ -v
    
    - name: Run MIMO benchmarks
      run: |
        PYTHONPATH=. python verticals/telecom/benchmarks/mimo_throughput_bench.py --quick

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: |
        pip install ruff mypy
        ruff check verticals/telecom/
        mypy verticals/telecom/ --ignore-missing-imports
